### ISSUE TITLE
Plugin is missing a descriptor properties file.

### ISSUE THREAD

**Issue by cuivier** [adiwajshing/kibana-json-content#1]
Hi,
i got this error while installing this plugin using bin/elasticsearch-plugin:

> 0.667 -> Installing https://github.com/adiwajshing/kibana-json-content/raw/refs/heads/master/build/jsonContent-8.15.0.zip                                        
> 0.667 -> Downloading https://github.com/adiwajshing/kibana-json-content/raw/refs/heads/master/build/jsonContent-8.15.0.zip                                       
> 1.497 -> Failed installing https://github.com/adiwajshing/kibana-json-content/raw/refs/heads/master/build/jsonContent-8.15.0.zip
> 1.497 -> Rolling back https://github.com/adiwajshing/kibana-json-content/raw/refs/heads/master/build/jsonContent-8.15.0.zip
> 1.499 -> Rolled back https://github.com/adiwajshing/kibana-json-content/raw/refs/heads/master/build/jsonContent-8.15.0.zip
> 1.499 java.lang.IllegalStateException: Plugin [.installing-14881514501855386853] is missing a descriptor properties file.
> 1.499   at org.elasticsearch.plugins.PluginDescriptor.readFromProperties(PluginDescriptor.java:234)
> 1.499   at org.elasticsearch.plugins.cli.InstallPluginAction.loadPluginInfo(InstallPluginAction.java:864)
> 1.499   at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:924)
> 1.499   at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:255)
> 1.499   at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:90)
> 1.499   at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:55)
> 1.499   at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:95)
> 1.499   at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
> 1.500   at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:95)
> 1.500   at org.elasticsearch.cli.Command.main(Command.java:52)
> 1.500   at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:65)

I am building this using docker elasticsearch image , version 8.15.0

**Comment by cuivier** [comment]
Nvm, i was using wrong docker image.
